### ISSUE TITLE
TokenUpdateNftsTransaction() returns TypeError

### ISSUE THREAD

**Issue by nadineloepfe** [hashgraph/hedera-wallet-connect#265]
**Describe the bug** 

I'm trying to run a TokenUpdateNftsTransaction() with WalletConnect and I'm running into this TypeError (see screenshot).
This only happens when using the signer/provider from WalletConnect – when testing this step with const client = Client.forTestnet().setOperator(operatorId, operatorKey) then it is successful in updating the metadata.
for ref - I've tried multiple versions of the syntax, all of them failing with the same error:
```
      const updateTransaction = new TokenUpdateNftsTransaction()
        .setTokenId(formattedTokenId)
        .setSerialNumbers([serialNumber])
        .setMetadata(new TextEncoder().encode(newMetadataUri))
        .freezeWith(hederaClient);
      
      const signedUpdateTx = await updateTransaction.sign(metadataKey);
      const txResult = await signedUpdateTx.executeWithSigner(signer);
```
as well as:
```
const updateTransaction = new TokenUpdateNftsTransaction()
      .setTokenId(tokenId) 
      .setSerialNumbers([serialNumber]) 
      .setMetadata(new TextEncoder().encode(newMetadataUri);) 

    await updateTransaction.freezeWithSigner(signer);
    const signedUpdateTx = await updateTransaction.sign(metadataKey);
    const txResult = await signedUpdateTx.executeWithSigner(signer);
```
it's always breaking at await signedUpdateTx.executeWithSigner(signer);
I am suspecting this may be an issue with WalletConnect.
Given this is a new transaction type it may be the wallet doesn’t support it yet.

**To Reproduce** Steps to reproduce the behavior:

1. login with wallet connect
2. specify inputs
3. click update and check console

[Example program](https://github.com/nadineloepfe/vanillajs-walletconnect/tree/update-metadata-e2e) to reproduce issue with one click (update-nft-metadata-e2e branch)
2. [Example Program](https://github.com/nadineloepfe/vanillajs-walletconnect/tree/update-nft-metadata) if pre-minted token shall be used (update-nft-metadata branch)
3. [Gist](https://gist.github.com/nadineloepfe/9c97eb56e46204164e8963d8fc60200f)

**Expected behavior** 
Metadata updating successfully

**Screenshots** 

<img width="833" alt="Screenshot 2024-09-10 at 23 12 25" src="https://github.com/user-attachments/assets/9308bd77-29a0-4388-8329-d18d3e76aba4">

**Desktop (please complete the following information):**

- OS: iOS
- Browser Chrome

**Comment by kantorcodes** [comment]
@nadineloepfe 

So the root of this issue was related to the Hedera SDK. Could you try with version `[v2.53.0-beta.4](https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.53.0-beta.4)` and see if that resolves your issue?

**Comment by nadineloepfe** [comment]
it unfortunately doesn't, @kantorcodes 

output:

```
{
  "txError": {},
  "queryError": {
    "name": "Error",
    "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
    "stack": "Error: (BUG) Query.fromBytes() not implemented for type getByKey\n    at Query.fromBytes (http://localhost:5173/node_modules/.vite/deps/chunk-5ICC4Y3K.js?v=c21a5bb8:67495:13)\n    at DAppSigner._tryExecuteQueryRequest (http://localhost:5173/node_modules/.vite/deps/@hashgraph_hedera-wallet-connect.js?v=157578fc:32323:27)\n    at DAppSigner.call (http://localhost:5173/node_modules/.vite/deps/@hashgraph_hedera-wallet-connect.js?v=157578fc:32342:36)\n    at async metadataUpdate (http://localhost:5173/main.js:226:22)\n    at async HTMLButtonElement.handleRunTest (http://localhost:5173/main.js:247:5)"
  }
}
```

**Comment by kantorcodes** [comment]
> it unfortunately doesn't, @kantorcodes
> 
> output:
> 
> ```
> {
>   "txError": {},
>   "queryError": {
>     "name": "Error",
>     "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
>     "stack": "Error: (BUG) Query.fromBytes() not implemented for type getByKey\n    at Query.fromBytes (http://localhost:5173/node_modules/.vite/deps/chunk-5ICC4Y3K.js?v=c21a5bb8:67495:13)\n    at DAppSigner._tryExecuteQueryRequest (http://localhost:5173/node_modules/.vite/deps/@hashgraph_hedera-wallet-connect.js?v=157578fc:32323:27)\n    at DAppSigner.call (http://localhost:5173/node_modules/.vite/deps/@hashgraph_hedera-wallet-connect.js?v=157578fc:32342:36)\n    at async metadataUpdate (http://localhost:5173/main.js:226:22)\n    at async HTMLButtonElement.handleRunTest (http://localhost:5173/main.js:247:5)"
>   }
> }
> ```

Hi! 

Could you confirm the full code snippet on your end as well as the packages you're using? You'll need the latest hashgraph SDK and canary release

```
   "@hashgraph/hedera-wallet-connect": "1.3.8-canary.25ba652.0",
```

**Comment by kantorcodes** [comment]
Hi @nadineloepfe I've added an example in this PR to demonstrate the TokenUpdateTransaction is working: 

https://github.com/hashgraph/hedera-wallet-connect/pull/362/files

Please take a look and see if you are able to get this working. In the meantime, I am closing this out. Feel free to reopen if you are still having issues.

**Comment by nadineloepfe** [comment]
apologies, I'm just picking this up again.

**Comment by tmctl** [comment]
@nadineloepfe

Here's a message from our team, can you reproduce in the repo provided below or let us know if there's something different that we're doing. Do you have a repo you can share with the most recent version of the library?



> on the latest version of @hashgraph/hedera-wallet-connect the bug is not reproducible. I copied the issue author's example project, which successfully produces NFT creation, NFT minting, and NFT metadata updates on latest packages version. Also fixes a small bug with an incorrect return of the NFT mint function, which did not return the expected serial number needed to update the metadata. The repository with bugfix and latest versions of @hashgraph/hedera-wallet-connect and @hashgraph/sdk can be found at:

> https://github.com/deligrim/vanillajs-walletconnect

> Here is a chain of successful transactions created by the project code:

> https://hashscan.io/testnet/transaction/1740497863.057313127 - TOKEN CREATE
> https://hashscan.io/testnet/transaction/1740497867.736076000 - TOKEN MINT
> https://hashscan.io/testnet/transaction/1740497872.565240482 - UPDATE NFTS

**Comment by moshenskyDV** [comment]
<img width="1572" alt="Image" src="https://github.com/user-attachments/assets/a714984c-14eb-4e0c-86bc-a9cafacf2b33" />

It isn't working on @nadineloepfe repo. Either for me in my projects. Keep facing this error. Tried several combinations of packages versions. Please do something with it.

```{
  "txError": {},
  "queryError": {
    "name": "Error",
    "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
    "stack": "Error: (BUG) Query.fromBytes() not implemented for type getByKey\n    at h.fromBytes (http://localhost:8100/static/js/bundle.js:57288:26)\n    at DAppSigner._tryExecuteQueryRequest (http://localhost:8100/static/js/bundle.js:28280:181)\n    at DAppSigner.call (http://localhost:8100/static/js/bundle.js:28311:36)\n    at async WalletConnect.executeTransaction (http://localhost:8100/static/js/bundle.js:308795:17)\n    at async sendTokens (http://localhost:8100/main.ede85cdb8e05af36593b.hot-update.js:183:32)"
  }
}
    at DAppSigner.call (DAppSigner.js:304:1)
    at async WalletConnect.executeTransaction (wallet-connect.ts:162:1)
    at async sendTokens (Swap.tsx:187:1)
```

**Comment by tmctl** [comment]
> <img alt="Image" width="1572" src="https://private-user-images.githubusercontent.com/15670713/423116138-a714984c-14eb-4e0c-86bc-a9cafacf2b33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUyNzI3MDAsIm5iZiI6MTc0NTI3MjQwMCwicGF0aCI6Ii8xNTY3MDcxMy80MjMxMTYxMzgtYTcxNDk4NGMtMTRlYi00ZTBjLTg2YmMtYTljYWZhY2YyYjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDIxVDIxNTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NjRlZGFmYWJlYzEzZjdmMDg3ZDM2YjE0MDExOTdhZWRiYjBmZjkyN2IxYWJkMDZmYTI4NzBmYjBkNTgwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9qxCIzxZ0GYHqfSSwtA1QP3A0eVZZdMbSdkDWLEuS0I">
> It isn't working on [@nadineloepfe](https://github.com/nadineloepfe) repo. Either for me in my projects. Keep facing this error. Tried several combinations of packages versions. Please do something with it.
> 
> ```
>   "txError": {},
>   "queryError": {
>     "name": "Error",
>     "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
>     "stack": "Error: (BUG) Query.fromBytes() not implemented for type getByKey\n    at h.fromBytes (http://localhost:8100/static/js/bundle.js:57288:26)\n    at DAppSigner._tryExecuteQueryRequest (http://localhost:8100/static/js/bundle.js:28280:181)\n    at DAppSigner.call (http://localhost:8100/static/js/bundle.js:28311:36)\n    at async WalletConnect.executeTransaction (http://localhost:8100/static/js/bundle.js:308795:17)\n    at async sendTokens (http://localhost:8100/main.ede85cdb8e05af36593b.hot-update.js:183:32)"
>   }
> }
>     at DAppSigner.call (DAppSigner.js:304:1)
>     at async WalletConnect.executeTransaction (wallet-connect.ts:162:1)
>     at async sendTokens (Swap.tsx:187:1)
> ```

hey @moshenskyDV - does it work for you in this repo? https://github.com/deligrim/vanillajs-walletconnect

**Comment by tmctl** [comment]
@nadineloepfe @moshenskyDV closing, please let us know if you are still running into the same issue with the provided repo in the comment above.
